name: Build and Upload Artifacts

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Install dependencies
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          gcc-arm-none-eabi \
          linaro-toolchain \
          libssl-dev \
          unzip \
          default-jdk \
          perl \
          binutils \
          adb

    # Set up Go
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20' # Update to the required Go version

    # Build using Makefile
    - name: Build Project
      run: make all

    # Upload build artifacts
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          ./cli
          ./kernelutil
          ./loader
          ./patcher
          ./patcher-payload.so
          ./getroot.elf
          ./decrypt
          ./third_party/apktool/apktool.jar
          ./third_party/dex2jar/d2j-dex2jar.sh
          ./third_party/procyon/procyon-decompiler.jar
          ./third_party/vdexExtractor/bin/vdexExtractor
